In [ ]:
#Required Libraries
import numpy as np  
from numpy.random import rand

In [ ]:
#dataset
x = np.array(([0.9,0.8],[0.6,0.3],[0.9,0.1],[0.9,0.8]))  #Features
y = np.array(([0],[1],[1],[0]))  #Labels (0,1)

In [ ]:
x

array([[0.9, 0.8],
       [0.6, 0.3],
       [0.9, 0.1],
       [0.9, 0.8]])

In [ ]:
# Activation function
def sigmoid(z):
    return 1/(1+np.exp(-z))

#Multi-layers feedforward neural network (2 hidden layers)
class NeuralNetwork:
    def __init__(self, x, y, nodes_in_layer1 = 4, nodes_in_layer2 = 3, nodes_in_layer3 = 1):
        #define x, y
        self.inputs_in_layer0 = x  #layer 0
        self.y = y
        
        #define and set the number of neurons in each layers
        self.nodes_in_layer1 = nodes_in_layer1
        self.nodes_in_layer2 = nodes_in_layer2
        self.nodes_in_layer3 = nodes_in_layer3
        
        #intialize the wieghts (theta) metrices
        self.thetas_layer0= np.random.rand(self.inputs_in_layer0.shape[1] + 1,self.nodes_in_layer1)  #shape: [2+1, 4]
        self.thetas_layer1 = np.random.rand(self.nodes_in_layer1 + 1,self.nodes_in_layer2)  #shape: [4+1, 3]
        self.thetas_layer2 = np.random.rand(self.nodes_in_layer2+1, nodes_in_layer3)  # shape: [3+1, 1]

    def feedforward(self):      
        #compute all the nodes (a1, a2, a3, a4) in layer1
        self.Z1 = self.thetas_layer0[0] + np.dot(self.inputs_in_layer0, self.thetas_layer0[1:])
        self.layer1 = sigmoid(self.Z1)  #values of a1, a2, a3, a4 in layer 1
        
        #compute all the nodes (a1, a2, a3) in layer2
        self.Z2 = self.thetas_layer1[0] + np.dot(self.layer1, self.thetas_layer1[1:])
        self.layer2 = sigmoid(self.Z2)  #values of a1, a2, a3 in layer 2
        
        #compute all the nodes (a1) in layer3
        self.Z3 = self.thetas_layer2[0] + np.dot(self.layer2, self.thetas_layer2[1:])
        self.layer3 = sigmoid(self.Z3)  #output layer
        
        return self.layer3 

In [ ]:
NN = NeuralNetwork(x,y)

predicted_output = NN.feedforward()
    
print ("Actual Output: \n", y)
print("Predicted Output: \n", predicted_output, "\n")

Actual Output: 
 [[0]
 [1]
 [1]
 [0]]
Predicted Output: 
 [[0.92341326]
 [0.92134993]
 [0.92163027]
 [0.92341326]] 

