In [1]:

import numpy as np
import pandas as pd

dataset = pd.read_csv('houses.csv')

dataset.head(20)


bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0        3.0       1.00       1180.0    5650.0     1.0         0.0   0.0   
1        3.0       2.25       2570.0    7242.0     2.0         0.0   0.0   
2        2.0       1.00        770.0   10000.0     1.0         0.0   0.0   
3        4.0       3.00       1960.0    5000.0     1.0         0.0   0.0   
4        3.0       2.00       1680.0    8080.0     1.0         0.0   0.0   
5        4.0       4.50       5420.0  101930.0     1.0         0.0   0.0   
6        3.0       2.25       1715.0    6819.0     2.0         0.0   0.0   
7        3.0       1.50       1060.0    9711.0     1.0         0.0   0.0   
8        3.0       1.00       1780.0    7470.0     1.0         0.0   0.0   
9        3.0       2.50       1890.0    6560.0     2.0         0.0   0.0   
10       3.0       2.50       3560.0    9796.0     1.0         0.0   0.0   
11       2.0       1.00       1160.0    6000.0     1.0         0.0   0.0   
12       3.0       1.00       1430.0   19901.0     1.5         0.0   0.0   
13       3.0       1.75       1370.0    9680.0     1.0         0.0   0.0   
14       5.0       2.00       1810.0    4850.0     1.5         0.0   0.0   
15       4.0       3.00       2950.0    5000.0     2.0         0.0   3.0   
16       3.0       2.00       1890.0   14040.0     2.0         0.0   0.0   
17       4.0       1.00       1600.0    4300.0     1.5         0.0   0.0   
18       2.0       1.00       1200.0    9850.0     1.0         0.0   0.0   
19       3.0       1.00       1250.0    9774.0     1.0         0.0   0.0   

    condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0         3.0    7.0      1180.0            0.0    1955.0           0.0   
1         3.0    7.0      2170.0          400.0    1951.0        1991.0   
2         3.0    6.0       770.0            0.0    1933.0           0.0   
3         5.0    7.0      1050.0          910.0    1965.0           0.0   
4         3.0    8.0      1680.0            0.0    1987.0           0.0   
5         3.0   11.0      3890.0         1530.0    2001.0           0.0   
6         3.0    7.0      1715.0            0.0    1995.0           0.0   
7         3.0    7.0      1060.0            0.0    1963.0           0.0   
8         3.0    7.0      1050.0          730.0    1960.0           0.0   
9         3.0    7.0      1890.0            0.0    2003.0           0.0   
10        3.0    8.0      1860.0         1700.0    1965.0           0.0   
11        4.0    7.0       860.0          300.0    1942.0           0.0   
12        4.0    7.0      1430.0            0.0    1927.0           0.0   
13        4.0    7.0      1370.0            0.0    1977.0           0.0   
14        3.0    7.0      1810.0            0.0    1900.0           0.0   
15        3.0    9.0      1980.0          970.0    1979.0           0.0   
16        3.0    7.0      1890.0            0.0    1994.0           0.0   
17        4.0    7.0      1600.0            0.0    1916.0           0.0   
18        4.0    7.0      1200.0            0.0    1921.0           0.0   
19        4.0    7.0      1250.0            0.0    1969.0           0.0   

    zipcode      lat     long  sqft_living15    price  
0   98178.0  47.5112 -122.257         1340.0   22.190  
1   98125.0  47.7210 -122.319         1690.0   53.800  
2   98028.0  47.7379 -122.233         2720.0   18.000  
3   98136.0  47.5208 -122.393         1360.0   60.400  
4   98074.0  47.6168 -122.045         1800.0   51.000  
5   98053.0  47.6561 -122.005         4760.0  123.000  
6   98003.0  47.3097 -122.327         2238.0   25.750  
7   98198.0  47.4095 -122.315         1650.0   29.185  
8   98146.0  47.5123 -122.337         1780.0   22.950  
9   98038.0  47.3684 -122.031         2390.0   32.300  
10  98007.0  47.6007 -122.145         2210.0   66.250  
11  98115.0  47.6900 -122.292         1330.0   46.800  
12  98028.0  47.7558 -122.229         1780.0   31.000  
13  98074.0  47.6127 -122.045         1370.0   

In [2]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp = imp.fit(dataset)
dataset = imp.transform(dataset)


X = dataset[:, :-1]
y = dataset[:, -1]

X
y

array([ 22.19      ,  53.8       ,  18.        ,  60.4       ,
        51.        , 123.        ,  25.75      ,  29.185     ,
        22.95      ,  32.3       ,  66.25      ,  46.8       ,
        31.        ,  40.        ,  53.        ,  65.        ,
        39.5       ,  48.5       ,  18.9       ,  23.        ,
        38.5       , 200.        ,  28.5       ,  25.27      ,
        32.9       ,  23.3       ,  93.7       ,  66.7       ,
        43.8       ,  71.9       ,  58.05      ,  28.        ,
        68.75      ,  53.5       ,  32.25      ,  69.6       ,
        55.        ,  64.        ,  24.        ,  60.5       ,
        62.5       ,  77.5       ,  86.199     ,  68.5       ,
        30.9       ,  48.8       ,  21.049     ,  78.5       ,
        45.        , 135.        ,  22.8       ,  34.5       ,
        60.        ,  58.5       ,  92.        ,  88.5       ,
        29.25      ,  30.1       ,  95.1       ,  43.        ,
        65.        ,  28.9       ,  50.5       ,  54.9 

In [3]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

X_train
X_test
y_train
y_test

array([ 19.    ,  60.5   ,  36.    ,  26.99  ,  51.7534,  47.85  ,
        55.995 ,  29.    ,  16.66  ,  22.    ,  41.9   ,  38.    ,
        21.4   ,  52.425 ,  25.3   ,  29.15  ,  30.49  ,  72.    ,
        40.    ,  26.875 ,  21.5   ,  67.3   ,  31.5   , 160.    ,
        32.    , 103.    ,  55.5   ,  28.3   ,  83.99  , 132.    ,
        23.99  ,  51.995 ,  57.7   ,  43.75  ,  28.    ,  44.    ,
        50.7   ,  26.85  ,  80.    ,  43.    ,  18.6375,  24.75  ,
       238.    ,  76.5   ,  26.75  ,  77.    ,  45.1   ,  39.995 ,
        57.8   ,  41.995 ,  33.89  ,  18.5   ,  23.7   ,  53.    ,
        25.27  ,  58.05  ,  48.5   ,  66.25  ,  27.995 ,  32.5   ,
        26.5   ,  92.    ,  31.8888,  46.4   ,  43.55  ,  35.99  ,
        47.5   ,  46.7   , 104.    ,  53.    ,  18.85  ,  66.995 ,
        50.5   ,  45.9   ,  36.    ,  50.    ,  32.5   ,  60.5   ,
        68.5   ,  61.075 , 115.    ,  97.5   ,  36.5   ,  28.7   ,
        54.8   ,  31.5   ,  18.995 ,  40.5   ,  69.98  ,  74. 

In [5]:
from sklearn.linear_model import SGDRegressor
 #clf = linear_model.SGDRegressor( penalty = 'l2' , max_iter=1000, tol=1e-3 , loss = 'huber')
sgd = SGDRegressor( penalty = 'l2' , max_iter=1000, tol=1e-3 , loss = 'squared_loss')
#clf = linear_model.SGDRegressor( penalty = 'l1' , max_iter=1000, tol=1e-3 , loss = 'huber')
#clf = linear_model.SGDRegressor( penalty = 'l1' , max_iter=1000, tol=1e-3 , loss = 'squared_loss')


sgd.fit(X_train, y_train)

y_pred = sgd.predict(X_test) 
y_pred

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:169: FutureWarning: The loss 'squared_loss' was deprecated in v1.0 and will be removed in version 1.2. Use `loss='squared_error'` which is equivalent.
  FutureWarning,


array([ 25.18169286,  56.66698365,  40.09341831,  13.78798769,
       -12.82451614,  60.14176246,  41.82336375,  40.24522169,
        16.15649334,  33.66506117,  30.26259417,  46.86562319,
        12.42152745,  42.11836081,  26.90094272,  15.97812514,
        43.34636783,  62.67197771,  26.86429427,  11.34544688,
        21.41027334,  61.67664421,  63.20048028, 152.76531013,
        24.64133012, 106.0177911 ,  60.22828656,  21.40749663,
        88.84049727,  68.39213499,  10.89473437,  31.52346251,
        44.93804597,  38.86773751,  24.16915699,  36.46139432,
        45.94713292,  21.9734193 ,  88.54446827,  44.08703573,
        18.27001378,  32.26066854, 135.53458906,  80.66083406,
        39.09321392,  86.41996364,  56.49197065,  48.64033165,
        61.74487281,  38.9167719 ,  19.40892172,  19.18268358,
        21.8476909 ,  64.69092325,  11.73609011,  52.73039427,
        48.24366325,  84.46153463,  29.13133678,   8.39366364,
        15.7769217 ,  82.84607783,  46.68360693,  76.27

In [6]:

sgd.score(X_train,y_train)
sgd.score(X_test,y_test)


0.709966399397773

In [9]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)


268.74512780416876