In [1]:
# Importing the libraries
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('houses.csv')

dataset.head(20)

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0        3.0       1.00       1180.0    5650.0     1.0         0.0   0.0   
1        3.0       2.25       2570.0    7242.0     2.0         0.0   0.0   
2        2.0       1.00        770.0   10000.0     1.0         0.0   0.0   
3        4.0       3.00       1960.0    5000.0     1.0         0.0   0.0   
4        3.0       2.00       1680.0    8080.0     1.0         0.0   0.0   
5        4.0       4.50       5420.0  101930.0     1.0         0.0   0.0   
6        3.0       2.25       1715.0    6819.0     2.0         0.0   0.0   
7        3.0       1.50       1060.0    9711.0     1.0         0.0   0.0   
8        3.0       1.00       1780.0    7470.0     1.0         0.0   0.0   
9        3.0       2.50       1890.0    6560.0     2.0         0.0   0.0   
10       3.0       2.50       3560.0    9796.0     1.0         0.0   0.0   
11       2.0       1.00       1160.0    6000.0     1.0         0.0   0.0   
12       3.0       1.00       1430.0   19901.0     1.5         0.0   0.0   
13       3.0       1.75       1370.0    9680.0     1.0         0.0   0.0   
14       5.0       2.00       1810.0    4850.0     1.5         0.0   0.0   
15       4.0       3.00       2950.0    5000.0     2.0         0.0   3.0   
16       3.0       2.00       1890.0   14040.0     2.0         0.0   0.0   
17       4.0       1.00       1600.0    4300.0     1.5         0.0   0.0   
18       2.0       1.00       1200.0    9850.0     1.0         0.0   0.0   
19       3.0       1.00       1250.0    9774.0     1.0         0.0   0.0   

    condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0         3.0    7.0      1180.0            0.0    1955.0           0.0   
1         3.0    7.0      2170.0          400.0    1951.0        1991.0   
2         3.0    6.0       770.0            0.0    1933.0           0.0   
3         5.0    7.0      1050.0          910.0    1965.0           0.0   
4         3.0    8.0      1680.0            0.0    1987.0           0.0   
5         3.0   11.0      3890.0         1530.0    2001.0           0.0   
6         3.0    7.0      1715.0            0.0    1995.0           0.0   
7         3.0    7.0      1060.0            0.0    1963.0           0.0   
8         3.0    7.0      1050.0          730.0    1960.0           0.0   
9         3.0    7.0      1890.0            0.0    2003.0           0.0   
10        3.0    8.0      1860.0         1700.0    1965.0           0.0   
11        4.0    7.0       860.0          300.0    1942.0           0.0   
12        4.0    7.0      1430.0            0.0    1927.0           0.0   
13        4.0    7.0      1370.0            0.0    1977.0           0.0   
14        3.0    7.0      1810.0            0.0    1900.0           0.0   
15        3.0    9.0      1980.0          970.0    1979.0           0.0   
16        3.0    7.0      1890.0            0.0    1994.0           0.0   
17        4.0    7.0      1600.0            0.0    1916.0           0.0   
18        4.0    7.0      1200.0            0.0    1921.0           0.0   
19        4.0    7.0      1250.0            0.0    1969.0           0.0   

    zipcode      lat     long  sqft_living15    price  
0   98178.0  47.5112 -122.257         1340.0   22.190  
1   98125.0  47.7210 -122.319         1690.0   53.800  
2   98028.0  47.7379 -122.233         2720.0   18.000  
3   98136.0  47.5208 -122.393         1360.0   60.400  
4   98074.0  47.6168 -122.045         1800.0   51.000  
5   98053.0  47.6561 -122.005         4760.0  123.000  
6   98003.0  47.3097 -122.327         2238.0   25.750  
7   98198.0  47.4095 -122.315         1650.0   29.185  
8   98146.0  47.5123 -122.337         1780.0   22.950  
9   98038.0  47.3684 -122.031         2390.0   32.300  
10  98007.0  47.6007 -122.145         2210.0   66.250  
11  98115.0  47.6900 -122.292         1330.0   46.800  
12  98028.0  47.7558 -122.229         1780.0   31.000  
13  98074.0  47.6127 -122.045         1370.0   

In [3]:

from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp = imp.fit(dataset)
dataset = imp.transform(dataset)


In [4]:

X = dataset[:, :-1]
y = dataset[:, -1]

In [5]:
X

array([[ 3.00000000e+00,  1.00000000e+00,  1.18000000e+03, ...,
         4.75112000e+01, -1.22257000e+02,  1.34000000e+03],
       [ 3.00000000e+00,  2.25000000e+00,  2.57000000e+03, ...,
         4.77210000e+01, -1.22319000e+02,  1.69000000e+03],
       [ 2.00000000e+00,  1.00000000e+00,  7.70000000e+02, ...,
         4.77379000e+01, -1.22233000e+02,  2.72000000e+03],
       ...,
       [ 2.00000000e+00,  1.00000000e+00,  8.50000000e+02, ...,
         4.76707000e+01, -1.22328000e+02,  1.30000000e+03],
       [ 2.00000000e+00,  1.00000000e+00,  1.03000000e+03, ...,
         4.73738000e+01, -1.22057000e+02,  1.45000000e+03],
       [ 3.34934935e+00,  2.04579580e+00,  2.05139740e+03, ...,
         4.75497199e+01, -1.22207406e+02,  1.98681381e+03]])

In [6]:
y

array([ 22.19      ,  53.8       ,  18.        ,  60.4       ,
        51.        , 123.        ,  25.75      ,  29.185     ,
        22.95      ,  32.3       ,  66.25      ,  46.8       ,
        31.        ,  40.        ,  53.        ,  65.        ,
        39.5       ,  48.5       ,  18.9       ,  23.        ,
        38.5       , 200.        ,  28.5       ,  25.27      ,
        32.9       ,  23.3       ,  93.7       ,  66.7       ,
        43.8       ,  71.9       ,  58.05      ,  28.        ,
        68.75      ,  53.5       ,  32.25      ,  69.6       ,
        55.        ,  64.        ,  24.        ,  60.5       ,
        62.5       ,  77.5       ,  86.199     ,  68.5       ,
        30.9       ,  48.8       ,  21.049     ,  78.5       ,
        45.        , 135.        ,  22.8       ,  34.5       ,
        60.        ,  58.5       ,  92.        ,  88.5       ,
        29.25      ,  30.1       ,  95.1       ,  43.        ,
        65.        ,  28.9       ,  50.5       ,  54.9 

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [9]:
X_train

array([[ 0.76410982, -0.06349407, -0.73400006, ...,  0.62779056,
        -1.16617958, -0.53251627],
       [ 1.93848783, -0.41010927, -0.44102988, ..., -0.14651676,
         2.65668761, -0.48774365],
       [ 0.76410982,  1.66958189,  2.95066343, ...,  0.60304101,
         0.31132632,  3.34777718],
       ...,
       [-2.75902422, -1.79657004, -1.88334464, ..., -0.48593915,
        -0.82907872, -1.21902973],
       [ 0.76410982,  0.62973631, -0.38468946, ...,  0.06562223,
         0.31132632,  0.22861821],
       [-0.4102682 ,  0.28312112,  0.15617858, ...,  1.5795875 ,
         0.91380445,  0.87035905]])

In [10]:
X_test

array([[-1.58464621, -1.44995485, -1.60164254, ..., -0.37067696,
        -0.09749813, -0.77130356],
       [-0.4102682 , -0.41010927, -0.14805969, ...,  0.09602882,
         0.54801415,  0.55695074],
       [ 0.76410982,  0.62973631,  0.17871475, ..., -1.18741208,
         0.0531214 ,  0.33308765],
       ...,
       [ 0.76410982,  0.62973631,  0.12237433, ..., -1.71068826,
        -1.22355845,  0.10922457],
       [-0.4102682 , -0.41010927, -0.67765964, ..., -1.35924467,
        -0.52066729, -1.15933291],
       [-0.4102682 ,  0.62973631, -0.04664694, ...,  0.01400174,
         1.50193786, -0.44297104]])

In [11]:
y_train

array([ 48.5       ,  20.1       , 158.        ,  48.        ,
        22.19      ,  48.7       ,  44.        ,  25.995     ,
        79.5       ,  97.        ,  43.8924    ,  32.25      ,
        31.3       , 145.        , 112.        ,  48.2       ,
        45.1       ,  20.        ,  24.35      ,  35.        ,
        47.        ,  33.1       ,  43.165     , 133.        ,
        63.        ,  66.05      , 308.        ,  37.5       ,
        27.4975    ,  50.        ,  38.        ,  61.9       ,
        19.9       , 145.        ,  42.        ,  43.8       ,
        45.        ,  40.        ,  40.395     ,  43.8       ,
        37.15      ,  32.5       ,  66.5       ,  91.75      ,
        25.75      ,  56.        ,  31.5       ,  36.        ,
        23.4       ,  62.5       ,  80.        ,  92.15      ,
       136.        ,  47.5       ,  68.6       ,  80.        ,
        65.        ,  78.4       ,  64.        ,  39.        ,
       110.        ,  77.5       ,  70.        ,  68.  

In [12]:
y_test

array([ 19.    ,  60.5   ,  36.    ,  26.99  ,  51.7534,  47.85  ,
        55.995 ,  29.    ,  16.66  ,  22.    ,  41.9   ,  38.    ,
        21.4   ,  52.425 ,  25.3   ,  29.15  ,  30.49  ,  72.    ,
        40.    ,  26.875 ,  21.5   ,  67.3   ,  31.5   , 160.    ,
        32.    , 103.    ,  55.5   ,  28.3   ,  83.99  , 132.    ,
        23.99  ,  51.995 ,  57.7   ,  43.75  ,  28.    ,  44.    ,
        50.7   ,  26.85  ,  80.    ,  43.    ,  18.6375,  24.75  ,
       238.    ,  76.5   ,  26.75  ,  77.    ,  45.1   ,  39.995 ,
        57.8   ,  41.995 ,  33.89  ,  18.5   ,  23.7   ,  53.    ,
        25.27  ,  58.05  ,  48.5   ,  66.25  ,  27.995 ,  32.5   ,
        26.5   ,  92.    ,  31.8888,  46.4   ,  43.55  ,  35.99  ,
        47.5   ,  46.7   , 104.    ,  53.    ,  18.85  ,  66.995 ,
        50.5   ,  45.9   ,  36.    ,  50.    ,  32.5   ,  60.5   ,
        68.5   ,  61.075 , 115.    ,  97.5   ,  36.5   ,  28.7   ,
        54.8   ,  31.5   ,  18.995 ,  40.5   ,  69.98  ,  74. 

In [13]:

from sklearn.svm import SVR
clf = SVR(kernel = 'linear')
clf.fit(X_train, y_train)

SVR(kernel='linear')

In [14]:
clf.score(X_train, y_train)

0.650447892242232

In [15]:
y_pred = clf.predict(X_test) 
y_pred


array([ 24.23578877,  52.09680719,  39.86151573,  22.15951441,
         0.78553309,  52.09331461,  44.59779403,  43.47672612,
        20.87329547,  28.23444493,  33.69219773,  44.2850286 ,
        16.16594657,  44.67416461,  25.24691405,  20.7487003 ,
        37.34505129,  59.03973048,  31.22801353,  17.3437975 ,
        24.74275498,  59.47200214,  59.20883064, 139.37104791,
        28.28849159,  95.00250346,  56.25345312,  20.30255981,
        73.81465979,  65.22215266,  17.21103282,  38.21466422,
        41.24253806,  42.44788034,  29.62761135,  42.81981127,
        47.95529356,  24.54258331,  83.675633  ,  45.71163545,
        20.87961089,  30.91843185, 118.44584635,  73.55506356,
        37.75622429,  76.46122893,  52.78750527,  44.0273125 ,
        54.92049543,  42.73089186,  24.57511442,  22.78870366,
        24.91954977,  64.54404798,  15.730228  ,  51.91254412,
        49.60069739,  68.49143014,  27.85575313,  14.14210602,
        19.61705053,  73.23730144,  42.45380677,  66.27

In [16]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

9.624347647739576

In [17]:

from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)


311.89373461268065