In [1]:
# Importing the libraries
import numpy as np
import pandas as pd


In [2]:

dataset = pd.read_csv('satf.csv')

dataset.head(20)

high_GPA  math_SAT  verb_SAT  comp_GPA  univ_GPA
0       3.45       643       589      3.76      3.52
1       2.78       558       512      2.87      2.91
2       2.52       583       503      2.54      2.40
3       3.67       685       602      3.83      3.47
4       3.24       592       538      3.29      3.47
5       2.10       562       486      2.64      2.37
6       2.82       573       548      2.86      2.40
7       2.36       559       536      2.03      2.24
8       2.42       552       583      2.81      3.02
9       3.51       617       591      3.41      3.32
10      3.48       684       649      3.61      3.59
11      2.14       568       592      2.48      2.54
12      2.59       604       582      3.21      3.19
13      3.46       619       624      3.52      3.71
14      3.51       642       619      3.41      3.58
15      3.68       683       642      3.52      3.40
16      3.91       703       684      3.84      3.73
17      3.72       712       652      3.64      3.49
18      2.15       564       501      2.14      2.25
19      2.48       557       549      2.21      2.37

In [3]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp = imp.fit(dataset)
dataset = imp.transform(dataset)

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
dataset = sc.fit_transform(dataset)


In [5]:

X = dataset[:, :-1]
y = dataset[:, -1]

In [6]:
X

array([[ 0.72669875,  0.37238093, -0.15320031,  1.24749308],
       [-0.57646865, -1.2162901 , -1.38199444, -0.50926141],
       [-1.0821754 , -0.74903391, -1.52561973, -1.16064229],
       [ 1.15460446,  1.15737132,  0.05425844,  1.38566478],
       [ 0.3182433 , -0.58082169, -0.96707694,  0.3197688 ],
       [-1.89908631, -1.14152911, -1.79691194, -0.96325415],
       [-0.49866761, -0.93593639, -0.80749329, -0.52900023],
       [-1.39337956, -1.19759985, -0.99899367, -2.16732183],
       [-1.276678  , -1.32843158, -0.2489505 , -0.6276943 ],
       [ 0.84340031, -0.1135655 , -0.12128358,  0.55663457],
       [ 0.78504953,  1.13868107,  0.80430161,  0.95141086],
       [-1.82128527, -1.02938763, -0.10532521, -1.27907518],
       [-0.94602358, -0.35653872, -0.26490886,  0.16185828],
       [ 0.74614901, -0.07618501,  0.40534248,  0.77376153],
       [ 0.84340031,  0.35369068,  0.32555065,  0.55663457],
       [ 1.17405472,  1.11999082,  0.69259306,  0.77376153],
       [ 1.6214107 ,  1.

In [7]:
y

array([ 0.77999282, -0.59061185, -1.73652722,  0.66764817,  0.66764817,
       -1.80393401, -1.73652722, -2.09603009, -0.34345363,  0.33061424,
        0.93727532, -1.42196222,  0.03851816,  1.20690247,  0.91480639,
        0.51036567,  1.25184033,  0.71258603, -2.07356116, -1.80393401,
        0.26320745,  0.03851816,  0.24073852,  0.44295889,  0.98221318,
        1.43159176, -1.73652722, -2.16343687,  0.91480639,  0.75752389,
        1.00468211,  0.95974425,  1.0720889 ,  1.31924711, -2.0286233 ,
       -1.84887187, -0.00641969,  0.66764817, -0.38839149, -0.97258364,
        0.44295889,  0.82493068,  0.24073852,  0.48789674,  0.24073852,
        0.03851816, -1.46690008, -0.20864005, -0.36592256,  0.55530353,
        0.95974425, -1.73652722, -0.77036328, -1.78146508,  0.08345602,
       -2.09603009,  0.51036567, -0.23110898,  0.77999282,  0.66764817,
       -0.20864005,  0.46542781,  0.5328346 ,  1.04961997,  1.20690247,
       -0.36592256,  0.44295889, -1.8713408 ,  0.26320745,  0.51

In [10]:
from sklearn.svm import SVR
clf = SVR(kernel = 'rbf')
clf.fit(X, y)

SVR()

In [11]:
clf.score(X, y)

0.9264421615660576

In [12]:

y_pred = clf.predict([[3.48,684,649,3.61]]) 
y_pred


array([-0.02769145])