In [1]:
# Importing the libraries
import numpy as np
import pandas as pd


In [2]:

dataset = pd.read_csv('Earthquakes.csv')

dataset.head(20)

latitude  longitude   depth  mag  gap   dmin   rms  horizontalError  \
0     5.1033   125.3179   44.32  4.3  131  1.970  0.70              5.0   
1    -8.8535   117.1527  116.88  4.9   59  2.991  1.06              6.5   
2     4.7512    96.2239   10.00  5.3  148  0.862  1.29              6.6   
3   -10.1202   118.7274   10.00  4.5   86  3.764  0.95              7.6   
4     1.4361   127.0142  120.78  4.5  105  0.748  0.76              8.0   
5     0.6058   126.2786   40.52  4.4  113  1.100  0.37              8.4   
6    -9.1216   122.4742  142.29  5.2   54  0.536  0.95              3.5   
7    -1.3392    99.6884   45.74  4.7  186  2.135  0.59              9.0   
8     1.0990    98.9888  106.01  4.2  155  1.427  0.47              7.3   
9     7.1680   126.6065   76.31  4.7   81  6.398  0.89              9.1   
10   -7.5370   127.7248  148.79  4.9   52  3.569  1.09              7.8   
11   -6.3139   119.5984   15.05  4.3   79  3.488  0.89              8.1   
12   -0.2312   125.2095   51.20  5.5   46  2.376  0.97              6.3   
13   -4.5834   125.4204  498.01  4.6   47  4.401  0.79             10.6   
14   -7.8628   118.7906   15.18  5.3   53  2.986  1.07              5.8   
15   -7.8828   118.7427   22.63  4.6   72  3.021  0.90              6.1   
16   -6.5828   105.2779   95.52  4.3  141  3.890  0.76              9.1   
17    8.9111   126.5555   42.14  5.0   36  2.069  0.81              7.8   
18    9.0530   123.3007   70.39  4.3  116  7.634  0.73              6.5   
19    8.2840   127.4254   10.00  4.4  143  2.191  0.62             10.5   

    depthError  magError  meter  
0          9.3     0.126   18.0  
1          7.3     0.091   38.0  
2          1.8     0.073   18.0  
3          1.9     0.084   42.0  
4          6.6     0.089   37.0  
5          7.2     0.149   13.0  
6          6.2     0.071   19.0  
7          8.1     0.088   39.0  
8          4.8     0.122   19.0  
9          1.9     0.049  126.0  
10         5.1     0.120   22.0  
11         5.7     0.137   15.0  
12         7.2     0.071   19.0  
13         8.3     0.086   40.0  
14         3.9     0.079   54.0  
15         7.4     0.114   23.0  
16         9.1     0.111   23.0  
17         4.8     0.034  269.0  
18        10.1     0.099   29.0  
19         1.9     0.102   28.0

In [3]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp = imp.fit(dataset)
dataset = imp.transform(dataset)


In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
dataset = sc.fit_transform(dataset)

In [5]:

X = dataset[:, :-1]
y = dataset[:, -1]

In [6]:
X

array([[ 1.11009733,  0.6094858 , -0.44639344, ..., -1.23101894,
         0.68491471,  0.09052609],
       [-1.38056298, -0.20501984,  0.1144867 , ..., -0.65892819,
         0.16241702, -0.60576134],
       [ 1.04726334, -2.29273669, -0.71168294, ..., -0.62078881,
        -1.27445165, -0.96385201],
       ...,
       [-0.30217745, -1.69626184,  0.4838977 , ..., -0.92590388,
         0.26691656, -0.40682207],
       [-1.31057294,  0.24809955,  0.61499647, ..., -0.08683744,
        -0.20333137,  0.18999572],
       [-1.25155788,  0.0456203 ,  0.51180257, ..., -0.43009189,
        -0.59520464, -1.22247306]])

In [7]:
y

array([-0.42683887,  0.23053864, -0.42683887, ..., -0.09815011,
       -0.45970774,  1.8739824 ])

In [11]:
from sklearn.svm import SVR
clf = SVR(kernel = 'rbf')
clf.fit(X, y)

SVR()

In [12]:
clf.score(X,y)

0.8227470273341159

In [13]:

y_pred = clf.predict([[90,12,12,-5,54,0.3,0.9,3.5,16.2,10]]) 
y_pred



array([-0.15752804])